In [2]:
# we usually import tools at the top
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
sp500 = pd.read_csv('StockData/sp500.csv', parse_dates=True, date_format='%m/%d/%y', index_col='Date')
sp500

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [9]:
# Moving Average
sp500['ma_5'] = sp500['Close'].rolling(window=5).mean()
sp500['ma_20'] = sp500['Close'].rolling(window=20).mean()
sp500

,Open,High,Low,Close,Adj Close,Volume,ma_5,ma_20
Date,,,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000,NaN,NaN
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000,NaN,NaN
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000,NaN,NaN
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000,NaN,NaN
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000,1687.916016,NaN
...,...,...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000,2918.410010,2899.497486
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000,2920.660010,2900.438489
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000,2920.264014,2900.860986
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000,2916.914014,2900.858985
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000,2913.776025,2901.501489

In [11]:
# resample across ME month end apply some rules
rules = {'Open':'first', 'Close':'last', 'Volume':'sum'}
# here we create a new DataFrame from our existing DataFrame
monthly = sp500.resample('ME').agg(rules)
monthly

                   Open        Close       Volume
Date
2013-09-30  1687.260010  1681.550049   3308630000
2013-10-31  1682.410034  1756.540039  76647400000
2013-11-30  1758.699951  1805.810059  63628190000
2013-12-31  1806.550049  1848.359985  64958820000
2014-01-31  1845.859985  1782.589966  75871910000
...                 ...          ...          ...
2018-05-31  2642.959961  2705.270020  75617280000
2018-06-30  2718.699951  2718.370117  77439710000
2018-07-31  2704.949951  2816.290039  64542170000
2018-08-31  2821.169922  2901.520020  69238220000
2018-09-30  2896.959961  2913.979980  62492080000

[61 rows x 3 columns]

#### Merge Data from separate sources

In [17]:
aapl = pd.read_csv('StockData/aapl.csv', parse_dates=True, date_format='%m/%d/%y', index_col='Date')
ba = pd.read_csv('StockData/ba.csv', parse_dates=True, date_format='%m/%d/%y', index_col='Date')

In [19]:
# Create a new column for the ticker name
aapl['Ticker'] = 'aapl'
aapl
ba['Ticker'] = 'ba'

In [22]:
merged = ba.merge(aapl, left_on=['Date'], right_on=['Date'], suffixes=('_ba', '_aapl') )

In [24]:
merged

,Open_ba,High_ba,Low_ba,Close_ba,Adj Close_ba,Volume_ba,Ticker_ba,Open_aapl,High_aapl,Low_aapl,Close_aapl,Adj Close_aapl,Volume_aapl,Ticker_aapl
Date,,,,,,,,,,,,,,
2013-10-01,117.970001,118.300003,117.080002,117.750000,102.874680,2880700,ba,68.349998,69.877144,68.339996,69.708572,63.523125,88470900,aapl
2013-10-02,117.379997,117.839996,116.279999,117.839996,102.953323,2871900,ba,69.375717,70.257141,69.107140,69.937141,63.731426,72296000,aapl
2013-10-03,117.349998,117.489998,114.730003,115.239998,100.681778,4455100,ba,70.072861,70.335716,68.677139,69.058571,62.930801,80688300,aapl
2013-10-04,115.269997,117.260002,115.250000,117.199997,102.394180,3998000,ba,69.122856,69.228569,68.371429,69.004288,62.881340,64717100,aapl
2013-10-07,115.510002,117.169998,115.400002,116.690002,101.948601,3822000,ba,69.508568,70.378571,69.335716,69.678574,63.495800,78073100,aapl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-09-24,371.000000,371.890015,367.329987,367.989990,367.989990,2800200,ba,216.820007,221.259995,216.630005,220.789993,220.789993,27693400,aapl
2018-09-25,369.079987,370.459991,366.880005,367.230011,367.230011,2969200,ba,219.750000,222.820007,219.699997,222.190002,222.190002,24554400,aapl
2018-09-26,367.500000,368.559998,364.320007,365.029999,365.029999,2368600,ba,221.000000,223.750000,219.759995,220.419998,220.419998,23984700,aapl
2018-09-27,368.399994,368.970001,364.399994,367.390015,367.390015,2355900,ba,223.820007,226.440002,223.539993,224.949997,224.949997,30181200,aapl
2018-09-28,368.630005,374.220001,366.220001,371.899994,371.899994,3595800,ba,224.789993,225.839996,224.020004,225.740005,225.740005,22889300,aapl

In [26]:
# string formats
n = 1.2000098758
p = 400.562434
print(  f'The total {p:0.2f} takes interest {n:0.4f}' )

The total 400.56 takes interest 1.2000

In [33]:
sp500.sort_values(['Volume'], ascending=False)
sp500 # many features of Pandas do not persist
sp500.sort_values(['Volume'], inplace=True) # be careful - this changes my data structure
sp500

,Open,High,Low,Close,Adj Close,Volume,ma_5,ma_20
Date,,,,,,,,
2013-12-24,1828.020020,1833.319946,1828.020020,1833.319946,1833.319946,1307630000,1819.975976,1800.310998
2017-11-24,2600.419922,2604.209961,2600.419922,2602.419922,2602.419922,1349780000,2591.904004,2584.638525
2015-12-24,2063.520020,2067.360107,2058.729980,2060.989990,2060.989990,1411860000,2038.190015,2055.905511
2014-12-24,2083.250000,2087.560059,2081.860107,2081.879883,2081.879883,1416980000,2074.893945,2050.783002
2015-11-27,2088.820068,2093.290039,2084.129883,2090.110107,2090.110107,1466840000,2088.776025,2080.564014
...,...,...,...,...,...,...,...,...
2014-12-19,2061.040039,2077.850098,2061.030029,2070.649902,2070.649902,6465530000,2021.427978,2048.650507
2016-03-18,2041.160034,2052.360107,2041.160034,2049.580078,2049.580078,6503140000,2030.592017,1986.087000
2015-08-24,1965.150024,1965.150024,1867.010010,1893.209961,1893.209961,6612690000,2015.271997,2074.732513
2015-12-18,2040.810059,2040.810059,2005.329956,2005.550049,2005.550049,6683070000,2037.172021,2064.324011
2016-06-24,2103.810059,2103.810059,2032.569946,2037.410034,2037.410034,7597450000,2081.665991,2091.767999